package com.harnessapp.app.ui.theme

import androidx.compose.ui.graphics.Color

val DarkPrimary = Color(0xFF5EEAD4)
val DarkOnPrimary = Color(0xFF00382E)
val DarkPrimaryContainer = Color(0xFF005042)
val DarkOnPrimaryContainer = Color(0xFF7BFFE0)

val DarkSecondary = Color(0xFFB4CCC6)
val DarkOnSecondary = Color(0xFF1F3430)
val DarkSecondaryContainer = Color(0xFF364B47)
val DarkOnSecondaryContainer = Color(0xFFD0E8E2)

val DarkTertiary = Color(0xFFDCC5FF)
val DarkOnTertiary = Color(0xFF3A1772)
val DarkTertiaryContainer = Color(0xFF52308B)
val DarkOnTertiaryContainer = Color(0xFFF3DBFF)

val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)

val DarkBackground = Color(0xFF0F1514)
val DarkOnBackground = Color(0xFFDFE4E2)
val DarkSurface = Color(0xFF121918)
val DarkSurfaceDim = Color(0xFF121918)
val DarkSurfaceBright = Color(0xFF373E3C)
val DarkSurfaceContainerLowest = Color(0xFF0A0F0E)
val DarkSurfaceContainerLow = Color(0xFF161D1C)
val DarkSurfaceContainer = Color(0xFF1A2120)
val DarkSurfaceContainerHigh = Color(0xFF242B2A)
val DarkSurfaceContainerHighest = Color(0xFF2F3634)
val DarkOnSurface = Color(0xFFDFE4E2)
val DarkOnSurfaceVariant = Color(0xFFBEC9C6)
val DarkOutline = Color(0xFF899391)
val DarkOutlineVariant = Color(0xFF3E4947)

val LightPrimary = Color(0xFF006B58)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF7BFFE0)
val LightOnPrimaryContainer = Color(0xFF005042)

val LightSecondary = Color(0xFF4D635E)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD0E8E2)
val LightOnSecondaryContainer = Color(0xFF354B46)

val LightTertiary = Color(0xFF69489F)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFEADDFF)
val LightOnTertiaryContainer = Color(0xFF4D2C83)

val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

val LightBackground = Color(0xFFF5FBF8)
val LightOnBackground = Color(0xFF151D1B)
val LightSurface = Color(0xFFF5FBF8)
val LightSurfaceDim = Color(0xFFD5DBD9)
val LightSurfaceBright = Color(0xFFF5FBF8)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFEFF5F2)
val LightSurfaceContainer = Color(0xFFE9EFEC)
val LightSurfaceContainerHigh = Color(0xFFE3E9E6)
val LightSurfaceContainerHighest = Color(0xFFDDE3E0)
val LightOnSurface = Color(0xFF151D1B)
val LightOnSurfaceVariant = Color(0xFF3F4846)
val LightOutline = Color(0xFF6F7977)
val LightOutlineVariant = Color(0xFFBEC9C6)
